name: Test Workflow
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/custom-agent@v2
        with:
          egress-policy: audit
          allowed-endpoints: >
            github.com:443

      - uses: actions/checkout@v3

      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: feat,fix,chore

      - uses: fkirc/skip-duplicate-actions@v5
        with:
          do_not_skip: '["release"]'

      - uses: chetan/git-restore-mtime-action@v1
        with:
          pattern: '**/*'
          
      - uses: tj-actions/changed-files@v38
      - uses: tj-actions/changed-files@v47

      # commit sha test 
      - uses: tj-actions/changed-files@17f3fec1edef0c3916d59cbcee1585fcd457e456 # v38.0.0
      - uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5

  lint3:
    runs-on: ubuntu-latest-code
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/custom-agent@v2
        with:
          egress-policy: audit
          allowed-endpoints: >
            github.com:443

      - uses: actions/checkout@v1

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/custom-agent@v2
        with:
          egress-policy: audit
          allowed-endpoints: >
            github.com:443

      - uses: actions/checkout@v1

      - uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true

      - uses: tespkg/actions-cache/restore@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # ✅ Simplified Checkov step (no name, no id)
      - uses: bridgecrewio/checkov-action@v12
        continue-on-error: true
        with:
          directory: .
          output_format: sarif
          output_file_path: checkov.sarif

      - uses: google-github-actions/auth@v2
      - uses: hashicorp/setup-terraform@v3
      - uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518
      - uses: jdx/mise-action@v4
      - uses: arduino/setup-task@v3
      - uses: JarvusInnovations/background-action@v1
      - uses: bufbuild/buf-action@v1.4.0
      

  lint2:
    runs-on: ubuntu-latest-code
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/custom-agent@v2
        with:
          egress-policy: audit
          allowed-endpoints: >
            github.com:443

      - uses: actions/checkout@v1
      - uses: actions/checkout-test@v1

  lint5:
    runs-on: self-hosted
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/custom-agent@v2
        with:
          egress-policy: audit
          allowed-endpoints: >
            github.com:443

      - uses: actions/checkout@v1

  lint6:
    runs-on: gpu-rtx-5050
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/custom-agent@v2
        with:
          egress-policy: audit
          allowed-endpoints: >
            github.com:443

      - uses: actions/checkout@v1
      
  build2:
    runs-on: [self-hosted, linux, arm64]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/custom-agent@v2
        with:
          egress-policy: audit
          allowed-endpoints: >
            github.com:443

      - uses: actions/checkout@v3
      - run: echo "build"
      
  
